# -*- coding: utf-8 -*-
"""Forecasting Core.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7MrPssQmUdFzekGfYvAjX9KQ92nsoGv
"""

!pip install statsmodels openpyxl

import pandas as pd
from statsmodels.tsa.holtwinters import Holt
import matplotlib.pyplot as plt

path = "/content/operation_data_Rakeem.xlsx"
df = pd.read_excel(path)

df['Month'] = pd.to_datetime(df['Month'])
df = df.sort_values(['entity_name', 'Month']).reset_index(drop=True)

print("Columns:", df.columns.tolist())

ompanies = df['entity_name'].dropna().unique().tolist()
print(f"Number of companies: {len(companies)}")
print("First 5 companies:", companies[:5])

df.head()

company_name = companies[0]

print("Selected company:", company_name)
d = df[df['entity_name'] == company_name][['Month', 'Revenue']].copy()

d = d.sort_values('Month')
d = d.set_index('Month')
d = d[~d.index.duplicated(keep='last')]
d = d.asfreq('MS')
d['Revenue'] = d['Revenue'].ffill()

print("Ready for Holt — Data shape:")
display(d.head())
print("Last 5 available months:")
display(d.tail())

model = Holt(d['Revenue'])
fit = model.fit()
future_months = 3
forecast = fit.forecast(future_months)
print(f"Revenue forecast for the next {future_months} months for company {company_name}:")
display(forecast)

plt.figure(figsize=(8,5))

plt.plot(d.index, d['Revenue'], label='Actual Data', marker='o')

plt.plot(forecast.index, forecast.values, label='Forecast (Holt)', linestyle='--', marker='x')

plt.title(f'Revenue Forecast for Company: {company_name}')
plt.xlabel('Date')
plt.ylabel('Revenue')
plt.legend()
plt.grid(True)
plt.show()

companies = df['entity_name'].dropna().unique()


all_forecasts = []


future_months = 3


for name in companies:

    d = df[df['entity_name'] == name][['Month', 'Revenue']].copy()
    d['Month'] = pd.to_datetime(d['Month'])
    d = d.sort_values('Month')
    d = d.set_index('Month').asfreq('MS')
    d['Revenue'] = d['Revenue'].ffill()


    fit = Holt(d['Revenue']).fit()


    fc = fit.forecast(future_months)


    fc = fc.to_frame(name='Revenue_Forecast').reset_index().rename(columns={'index': 'Month'})
    fc['entity_name'] = name


    all_forecasts.append(fc)


forecast_df = pd.concat(all_forecasts, ignore_index=True)


print("Revenue forecast generated for all companies:")

display(forecast_df.head(15))